CREATE TABLESPACE PANDORA LOCATION '/var/lib/postgresql/tablespace';
CREATE DATABASE GESTMAT TABLESPACE PANDORA;

CREATE USER IF NOT EXISTS 'UDATAMOVEMENT'@'localhost' IDENTIFIED BY '1234';
GRANT INSERT,CREATE ON OLDGESTMAT.* TO 'UDATAMOVEMENT'@'%';

--psql -U udatamovement -d gestmat;

CREATE SCHEMA OLDGESTMAT;

CREATE SCHEMA PROD;

--sudo -u postgres sql

CREATE USER IF NOT EXISTS UCONSELLERIA WITH PASSWORD '1234';
ALTER DATABASE GESTMAT OWNER TO UCONSELLERIA;

\c gestmat

GRANT USAGE, CREATE ON SCHEMA OLDGESTMAT TO UCONSELLERIA;
GRANT USAGE, CREATE ON SCHEMA PROD TO UCONSELLERIA;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA OLDGESTMAT TO UCONSELLERIA;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PROD TO UCONSELLERIA;

ALTER DEFAULT PRIVILEGES IN SCHEMA OLDGESTMAT GRANT ALL PRIVILEGES ON TABLES TO UCONSELLERIA;
ALTER DEFAULT PRIVILEGES IN SCHEMA PROD GRANT ALL PRIVILEGES ON TABLES TO UCONSELLERIA;

--psql -U uconselleria -d gestmat;



