

-- Mover datos de CORR_ELECT
INSERT INTO prod.CORR_ELECT (ID, CORR_ELECT)
SELECT ID, CORR_ELECT
FROM oldgestmat.CORR_ELECT;

-- Mover datos de CURS
INSERT INTO prod.CURS (ID)
SELECT ID
FROM oldgestmat.CURS;

-- Mover datos de ASSIGNATURA
INSERT INTO prod.ASSIGNATURA (NOM)
SELECT UPPER(NOM)
FROM oldgestmat.ASSIGNATURA;

-- Mover datos de DENOM_GEN
INSERT INTO prod.DENOM_GEN (NOM)
SELECT NOM
FROM oldgestmat.DENOM_GEN;

-- Mover datos de COM_AUT
INSERT INTO prod.COM_AUT (NOM)
SELECT NOM
FROM oldgestmat.COM_AUT;

-- Mover datos de TIPO_ENSNY
INSERT INTO prod.TIPO_ENSNY (NOM)
SELECT NOM
FROM oldgestmat.TIPO_ENSNY;

-- Mover datos de DISTRIT
INSERT INTO prod.DISTRIT (ID)
SELECT ID
FROM oldgestmat.DISTRIT;

-- Mover datos de MODALITAT
INSERT INTO prod.MODALITAT (NOM)
SELECT NOM
FROM oldgestmat.MODALITAT;

-- Mover datos de GRUP
INSERT INTO prod.GRUP (ID)
SELECT ID
FROM oldgestmat.GRUP;

-- Mover datos de TITULAR
INSERT INTO prod.TITULAR (NIF, NOM)
SELECT NIF, NOM
FROM oldgestmat.TITULAR;

-- Mover datos de MUNICIPI
INSERT INTO prod.MUNICIPI (NOM, COM_AUT)
SELECT NOM, COM_AUT
FROM oldgestmat.MUNICIPI;

-- Mover datos de ILLA
INSERT INTO prod.ILLA (NOM,COM_AUT)
SELECT NOM,COM_AUT
FROM oldgestmat.ILLA;

-- Mover datos de CODI_POSTAL
INSERT INTO prod.CODI_POSTAL (CP, MUNICIPI)
SELECT CP, MUNICIPI
FROM oldgestmat.CODI_POSTAL;

-- Mover datos de LOCALITAT
INSERT INTO prod.LOCALITAT (NOM)
SELECT NOM
FROM oldgestmat.LOCALITAT;

-- Mover datos de ESTUDIANT
INSERT INTO prod.ESTUDIANT (DNI, NOM, EMAIL, COGNOM, COGNOM_AD, MUNICIPI)
SELECT DNI, NOM, EMAIL, COGNOM, COGNOM_AD, MUNICIPI
FROM oldgestmat.ESTUDIANT;

-- Mover datos de CENTRE
INSERT INTO prod.CENTRE (ID, NOM_CENTRE, TELEFON, WEB, TITULAR, CP)
SELECT ID, NOM_CENTRE, TELEFON, WEB, TITULAR, CP
FROM oldgestmat.CENTRE;

-- Mover datos de ADRECA
INSERT INTO prod.ADRECA (NOM, LOCALITAT,CENTRE)
SELECT NOM, LOCALITAT,CENTRE
FROM oldgestmat.ADRECA;

-- Mover datos de MATRICULA
INSERT INTO prod.MATRICULA (ESTUDIANT, TIPO_ENSNY, CENTRE, CURS, ASSIGNATURA, MODALITAT, GRUP)
SELECT ESTUDIANT, TIPO_ENSNY, CENTRE, CURS, 
    UPPER(TRIM(ASSIGNATURA)),
     MODALITAT, GRUP
FROM oldgestmat.MATRICULA;

-- Mover datos de R_CENTRE_CORREU
INSERT INTO prod.R_CENTRE_CORREU (CENTRE, CORREU)
SELECT CENTRE, CORREU
FROM oldgestmat.R_CENTRE_CORREU;

-- Mover datos de R_MUNICIPI_DISTRIT
INSERT INTO prod.R_MUNICIPI_DISTRIT (MUNICIPI, DISTRIT)
SELECT MUNICIPI, DISTRIT
FROM oldgestmat.R_MUNICIPI_DISTRIT;

-- Mover datos de R_MUNICIPI_DISTRIT
INSERT INTO prod.R_MUNICIPI_LOCALITAT (MUNICIPI, LOCALITAT)
SELECT MUNICIPI, LOCALITAT
FROM oldgestmat.R_MUNICIPI_LOCALITAT;