CREATE TABLE prod.CORR_ELECT(
    ID SERIAL PRIMARY KEY,
    CORR_ELECT VARCHAR
)TABLESPACE PANDORA;

CREATE TABLE prod.CURS(
    ID INT PRIMARY KEY
)TABLESPACE PANDORA;

CREATE TABLE prod.ASSIGNATURA(
    NOM VARCHAR PRIMARY KEY
    
)TABLESPACE PANDORA;

CREATE TABLE prod.DENOM_GEN(
    NOM VARCHAR PRIMARY KEY 
)TABLESPACE PANDORA;

CREATE TABLE prod.COM_AUT(
    NOM VARCHAR PRIMARY KEY    
)TABLESPACE PANDORA;

CREATE TABLE prod.TIPO_ENSNY(
    NOM VARCHAR(8) PRIMARY KEY 
)TABLESPACE PANDORA;

CREATE TABLE prod.DISTRIT(
    ID INT PRIMARY KEY
)TABLESPACE PANDORA;


CREATE TABLE prod.MODALITAT(
    NOM VARCHAR PRIMARY KEY  
)TABLESPACE PANDORA;

CREATE TABLE prod.GRUP(
    ID CHAR PRIMARY KEY
)TABLESPACE PANDORA;

CREATE TABLE prod.TITULAR(
    NIF VARCHAR(16) PRIMARY KEY,
    NOM VARCHAR
)TABLESPACE PANDORA;

CREATE TABLE prod.ILLA (
    NOM VARCHAR PRIMARY KEY,
    COM_AUT VARCHAR NOT NULL,
    FOREIGN KEY (COM_AUT) REFERENCES prod.com_aut(NOM)
    
)TABLESPACE PANDORA;

CREATE TABLE prod.MUNICIPI(
    ID SERIAL PRIMARY KEY,
    NOM VARCHAR,
    COM_AUT VARCHAR,
    FOREIGN KEY (COM_AUT) REFERENCES prod.com_aut(NOM))TABLESPACE PANDORA;

CREATE TABLE prod.CODI_POSTAL (
    CP VARCHAR(8) PRIMARY KEY,
    MUNICIPI INT,
    FOREIGN KEY (MUNICIPI) REFERENCES prod.MUNICIPI(ID)
)TABLESPACE PANDORA;

CREATE TABLE prod.LOCALITAT(
    ID SERIAL PRIMARY KEY,
    NOM VARCHAR,
    MUNICIPI INT,
    FOREIGN KEY (MUNICIPI) REFERENCES prod.MUNICIPI(ID)
    )TABLESPACE PANDORA;


CREATE TABLE prod.ESTUDIANT(
    DNI VARCHAR(16) PRIMARY KEY,
    NOM VARCHAR,
    EMAIL VARCHAR,
    COGNOM VARCHAR,
    COGNOM_AD VARCHAR,
    MUNICIPI INT,
    FOREIGN KEY (MUNICIPI) REFERENCES prod.MUNICIPI(ID)
)TABLESPACE PANDORA;

CREATE TABLE prod.CENTRE(
    ID INT PRIMARY KEY,
    NOM_CENTRE VARCHAR,
    TELEFON INT,
    WEB VARCHAR,
    TITULAR VARCHAR(16),
    CP VARCHAR(8),
    FOREIGN KEY (TITULAR) REFERENCES prod.TITULAR(NIF)
)TABLESPACE PANDORA;

CREATE TABLE prod.ADRECA(
    ID SERIAL PRIMARY KEY,
    NOM VARCHAR,
    LOCALITAT INT,
    CENTRE INT,
    FOREIGN KEY (CENTRE) REFERENCES prod.CENTRE(ID),
    FOREIGN KEY (LOCALITAT) REFERENCES prod.LOCALITAT(ID)  
)TABLESPACE PANDORA;

CREATE TABLE prod.MATRICULA(
    ID SERIAL PRIMARY KEY,
    ESTUDIANT VARCHAR(16),
    TIPO_ENSNY VARCHAR,
    CENTRE INT,
    CURS INT,
    ASSIGNATURA VARCHAR,
    MODALITAT VARCHAR,
    GRUP CHAR,
    FOREIGN KEY (ESTUDIANT) REFERENCES prod.ESTUDIANT(DNI),
    FOREIGN KEY (TIPO_ENSNY) REFERENCES prod.TIPO_ENSNY(NOM),
    FOREIGN KEY (CENTRE) REFERENCES prod.CENTRE(ID),
    FOREIGN KEY (CURS) REFERENCES prod.CURS(ID),
    FOREIGN KEY (ASSIGNATURA) REFERENCES prod.ASSIGNATURA(NOM),
    FOREIGN KEY (MODALITAT) REFERENCES prod.MODALITAT(NOM),
    FOREIGN KEY (GRUP) REFERENCES prod.GRUP(ID)
)TABLESPACE PANDORA;

CREATE TABLE prod.R_CENTRE_CORREU(
    CENTRE INT,
    CORREU INT,
    FOREIGN KEY (CENTRE) REFERENCES prod.CENTRE(ID),
    FOREIGN KEY (CORREU) REFERENCES prod.CORR_ELECT(ID),
    CONSTRAINT ID_CENTRE_CORREU PRIMARY KEY (CENTRE,CORREU)
)TABLESPACE PANDORA;

CREATE TABLE prod.R_MUNICIPI_DISTRIT(
    MUNICIPI INT,
    DISTRIT INT,
    FOREIGN KEY (MUNICIPI) REFERENCES prod.MUNICIPI(ID),
    FOREIGN KEY(DISTRIT) REFERENCES prod.DISTRIT(ID),
    CONSTRAINT ID_MUNICIPI_CP PRIMARY KEY(MUNICIPI, DISTRIT)
)TABLESPACE PANDORA;

CREATE TABLE prod.R_MUNICIPI_LOCALITAT(
    MUNICIPI INT,
    LOCALITAT INT,
    FOREIGN KEY (MUNICIPI) REFERENCES prod.MUNICIPI(ID),
    FOREIGN KEY(LOCALITAT) REFERENCES prod.LOCALITAT(ID),
    CONSTRAINT ID_MUNICIPI_CP PRIMARY KEY(MUNICIPI, LOCALITAT)
)TABLESPACE PANDORA;
