--\r\n si el sistema es CRLF

LOAD DATA INFILE '/var/lib/mysql-files/Llistat_CENTRES.csv' 
INTO TABLE CENTRE 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS (`CODI`,`DENOM_GEN`,`NOM`,`EMAIL`,`EMAIL_LIST`,`WEB`,`TITULAR`,`NIF`,`LOCALITAT`,`MUNICIPI`,`ADREC`,`CP`,`ILLA`,`TELEFON`);

LOAD DATA INFILE '/var/lib/mysql-files/estudiants.csv'
INTO TABLE ESTUDIANT
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS 
(DNI, NOM, COGNOM_1, COGNOM_2, EMAIL, CP_DISTR, COM_AUT, @RAW_MUNICIPI)
SET MUNICIPI = IF(LOCATE(',', @RAW_MUNICIPI) > 0, 
                  CONCAT(SUBSTRING_INDEX(@RAW_MUNICIPI, ', ', -1), ' ', SUBSTRING_INDEX(@RAW_MUNICIPI, ', ', 1)), 
                  @RAW_MUNICIPI);


LOAD DATA INFILE '/var/lib/mysql-files/matricules_202425.csv' 
INTO TABLE MATRICULA 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS (`DNI`,`TIPO_ENSNY`,`MODALITAT`,`CURS`,`ASSIGNATURA`,`GRUP`,`CODI_CENTRE`);