/*  Permisos: INSERTAR DATOA Y CREAR ESTRUCTURAS
        DATABASE: RAW IMPORT
*/

CREATE USER IF NOT EXISTS 'IMPORTADOR_1'@'localhost' IDENTIFIED BY '1234';
GRANT INSERT,CREATE ON RAW_IMPORT.* TO 'IMPORTADOR_1'@'%';

/*  Permisos: CONSULTAR DATOS
        DATABASE: RAW IMPORT

    Permisos:INSERTAR DATOS; CREAR ESTRUCTURAS Y CONSULTAR DATOS
        DATABASE:GESTMAT
*/

CREATE USER IF NOT EXISTS 'TRANSFORMADOR_1'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '1234';
GRANT INSERT,CREATE,SELECT ON GESTMAT.* TO 'TRANSFORMADOR_1'@'%';
GRANT SELECT ON RAW_IMPORT.* TO 'TRANSFORMADOR_1'@'%';
